name: Pipeline Teste API

on: push

jobs:
    tests:
        runs-on: uruntu-latest

        steps:
          - name: Clonagem Projeto
            uses: actions/checkout@v3

          - name: Configuração do Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.12'


